.level=INFO

handlers=java.util.logging.ConsoleHandler, java.util.logging.FileHandler


java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=logdemo.GlobalCustomFormatter
java.util.logging.ConsoleHandler.encoding=UTF-8

java.util.logging.FileHandler.level=ALL
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.FileHandler.pattern=jul_logging_%g.log
java.util.logging.FileHAndler.limit=1028
java.util.logging.FileHandler.count=5
java.util.logging.FilaHandler.append=true
java.util.logging.FileHandler.encoding=UTF-8


logdemo.level=ALL
logdemo.handlers=java.util.logging.ConsoleHandler ,java.util.logging.FileHandler

java.util.logging.SimpleFormatter.format=[%1$tF %1$tT] [%2$-7s] %3$-20s: %4$s %n